# Generated by Django 3.1.7 on 2021-06-18 11:58

import Movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieID', models.CharField(default=Movie.models.generateUniqueCode, max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('minAge', models.PositiveIntegerField()),
                ('video', models.FileField(default=None, upload_to='videos/')),
                ('trailer', models.FileField(null=True, upload_to='trailer/')),
                ('thumbnail', models.FileField(null=True, upload_to='thumbnail/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
